# Generated by Django 5.2.8 on 2025-11-26 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_customuser_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('candidate', 'Candidate'), ('manager', 'Recruiter'), ('sme', 'Subject Matter Expert'), ('administrator', 'administrator')], max_length=50),
        ),
    ]
