# Generated by Django 5.2.8 on 2025-12-26 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_customuser_role'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='customuser',
            name='users_custo_role_6a37b1_idx',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='access_level',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='username',
        ),
        migrations.AddField(
            model_name='customuser',
            name='dob',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('candidate', 'Candidate'), ('manager', 'Manager'), ('sme', 'SME'), ('administrator', 'Administrator')], default='candidate', max_length=50),
        ),
    ]
