# Generated by Django 5.2.8 on 2026-01-04 22:41

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('users', '0005_alter_customuser_managers_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='customuser',
            name='users_custo_email_c80f75_idx',
        ),
        migrations.AddField(
            model_name='customuser',
            name='is_temp_password',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='date_joined',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AddIndex(
            model_name='customuser',
            index=models.Index(fields=['email', 'id'], name='users_custo_email_c228ac_idx'),
        ),
    ]
