# Generated by Django 5.2.7 on 2025-11-06 06:12

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='data',
        ),
        migrations.AlterField(
            model_name='question',
            name='difficulty',
            field=models.PositiveSmallIntegerField(default=1, help_text='1 = easy, 5 = expert', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)]),
        ),
        migrations.CreateModel(
            name='CasePayload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rubric', models.JSONField(default=dict, help_text='{"criteria": "Safety", "max": 5, "weight": 0.4}')),
                ('question', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='case_payload', to='questions.question')),
            ],
        ),
        migrations.CreateModel(
            name='DiagramPayload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='diagrams/')),
                ('hotspots', models.JSONField(default=list)),
                ('question', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='diag_payload', to='questions.question')),
            ],
        ),
        migrations.CreateModel(
            name='MCQPayload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('options', models.JSONField(default=list, help_text='["A", "B", "C", "D"]')),
                ('correct', models.JSONField(default=list, help_text='Exact text of correct option')),
                ('shuffle', models.BooleanField(default=True)),
                ('question', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='mcq_payload', to='questions.question')),
            ],
            options={
                'db_table': 'questions_mcq_payload',
            },
        ),
        migrations.CreateModel(
            name='NumericalPayload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer', models.FloatField()),
                ('unit', models.CharField(blank=True, max_length=20)),
                ('tolerance', models.FloatField(default=0.02, help_text='Relative tolerance (e.g., 0.02 = ±2%)')),
                ('question', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='num_payload', to='questions.question')),
            ],
        ),
    ]
