# Generated by Django 5.2.7 on 2025-11-06 06:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0002_remove_question_data_alter_question_difficulty_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='mcqpayload',
            table=None,
        ),
    ]
