# Generated by Django 5.2.8 on 2025-11-26 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0003_alter_mcqpayload_table'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='domain',
            options={'ordering': ['name'], 'verbose_name': 'Domains'},
        ),
        migrations.AlterField(
            model_name='domain',
            name='slug',
            field=models.SlugField(blank=True, help_text='URL-safe identifier', unique=True),
        ),
    ]
