# Generated by Django 5.2.8 on 2025-12-19 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0005_alter_topic_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mcqpayload',
            name='correct',
            field=models.JSONField(default=list, help_text='List of IDs of correct option(s)'),
        ),
        migrations.AlterField(
            model_name='mcqpayload',
            name='options',
            field=models.JSONField(default=dict, help_text='Dictionary of options, e.g., {"uuid1": "Option A", "uuid2": "Option B"}'),
        ),
    ]
