# Generated by Django 5.2.8 on 2025-12-20 04:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0006_alter_mcqpayload_correct_alter_mcqpayload_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mcqpayload',
            name='correct',
            field=models.JSONField(default=dict, help_text='List of IDs of correct option(s)'),
        ),
    ]
