# Generated by Django 5.2.8 on 2025-12-20 06:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0007_alter_mcqpayload_correct'),
    ]

    operations = [
        migrations.RenameField(
            model_name='question',
            old_name='explanation',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='question',
            old_name='text',
            new_name='question',
        ),
    ]
